/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "secondary-fixed": "#ffdbc8",
        "on-primary-fixed": "#001c37",
        "primary-container": "#0a2540",
        "surface-dim": "#d8dadc",
        "primary-fixed-dim": "#b0c8eb",
        "secondary-container": "#fb7800",
        "surface-bright": "#f7f9fb",
        "secondary": "#994700",
        "inverse-on-surface": "#eff1f3",
        "tertiary-container": "#012544",
        "tertiary-fixed-dim": "#acc9ef",
        "on-error": "#ffffff",
        "on-tertiary-container": "#718db1",
        "on-primary-container": "#768dad",
        "inverse-primary": "#b0c8eb",
        "on-secondary": "#ffffff",
        "surface-tint": "#49607e",
        "secondary-fixed-dim": "#ffb68b",
        "on-primary-fixed-variant": "#314865",
        "surface": "#f7f9fb",
        "tertiary-fixed": "#d2e4ff",
        "on-tertiary-fixed": "#001d36",
        "error": "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c4c6ce",
        "on-background": "#191c1e",
        "on-secondary-fixed-variant": "#753400",
        "surface-variant": "#e0e3e5",
        "on-tertiary-fixed-variant": "#2c4869",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#592600",
        "surface-container": "#eceef0",
        "on-surface-variant": "#43474d",
        "outline": "#74777e",
        "primary-fixed": "#d2e4ff",
        "primary": "#000f22",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-surface": "#2d3133",
        "tertiary": "#000f21",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "background": "#f7f9fb",
        "on-secondary-fixed": "#321200"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "container-max": "1280px",
        "section-padding": "80px",
        "gutter": "24px",
        "stack-sm": "8px",
        "margin-mobile": "16px",
        "stack-lg": "32px",
        "stack-md": "16px"
      },
      "fontSize": {
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "h2": ["36px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "h3": ["24px", {"lineHeight": "1.3", "letterSpacing": "0", "fontWeight": "600"}],
        "button": ["16px", {"lineHeight": "1", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
